# Generated by Django 3.2.18 on 2023-06-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgeons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeon',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Workschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('beforedinner', models.CharField(max_length=255)),
                ('dinner', models.CharField(max_length=255)),
                ('afterdinner', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('surg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgeons.surgeon')),
            ],
        ),
    ]
