# Generated by Django 3.2.18 on 2023-06-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surgeons', '0002_auto_20230601_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptiondays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=255)),
                ('tuesday', models.CharField(max_length=255)),
                ('wensday', models.CharField(max_length=255)),
                ('thursday', models.CharField(max_length=255)),
                ('friday', models.CharField(max_length=255)),
                ('surg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgeons.surgeon')),
            ],
        ),
    ]
