# Generated by Django 3.2.18 on 2023-06-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeons', '0003_receptiondays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptiondays',
            name='friday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receptiondays',
            name='monday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receptiondays',
            name='thursday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receptiondays',
            name='tuesday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receptiondays',
            name='wensday',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
